# EXAMPLE VAULT FILE - Copy this to vault.py and fill in your credentials
credentials = {
    "dev": {
        "EMAIL": "your-email@example.com",
        "PASSWORD": "your-email-password",
        "S3_BUCKET": "your-s3-bucket",
        "AWS_ACCESS_KEY_ID": "your-aws-access-key",
        "AWS_SECRET_ACCESS_KEY": "your-aws-secret-key",
        "REGION": "us-east-1",
        "AWS_URL": "https://your-bucket.s3.amazonaws.com",
        "DB_ENGINE": "django.db.backends.postgresql",
        "DB_NAME": "postgres",
        "DB_USER": "postgres",
        "DB_PASSWORD": "postgres",
        "DB_HOST": "db",
        "DB_PORT": 5432,
        "FRONTEND_BASE_URL": "http://localhost:3000",
        "ADMIN_FRONTEND_BASE_URL": "http://localhost:3000",
    },
    "prod": {
        "EMAIL": "your-email@example.com",
        "PASSWORD": "your-email-password",
        "S3_BUCKET": "your-s3-bucket-prod",
        "AWS_ACCESS_KEY_ID": "your-aws-access-key-prod",
        "AWS_SECRET_ACCESS_KEY": "your-aws-secret-key-prod",
        "REGION": "us-east-1",
        "AWS_URL": "https://your-bucket-prod.s3.amazonaws.com",
        "DB_ENGINE": "django.db.backends.postgresql",
        "DB_NAME": "postgres",
        "DB_USER": "postgres",
        "DB_PASSWORD": "postgres",
        "DB_HOST": "db",
        "DB_PORT": 5432,
        "FRONTEND_BASE_URL": "https://your-production-domain.com",
        "ADMIN_FRONTEND_BASE_URL": "https://your-production-domain.com",
    },
}
